"""Canonical logical data-domain entry points for EMSX.

This package defines the shared adapter layer between:

- Execution operational persistence and warm-start data
- CostView analytical queries and reporting

The goal is to keep business domains separate while exposing one stable
integration surface for code that needs platform data access.
"""

from .adapters import (
    CostViewAnalyticsAdapter,
    ExecutionOperationalDataAdapter,
    MarketReferenceDataAdapter,
    PlatformDataAccess,
    build_platform_data_access,
    # Market reference types
    MarketAlert,
    MarketCandidatePayload,
    MarketCandidateRow,
    MarketDailySnapshotRow,
    MarketSnapshot,
    MarketSnapshotFilters,
    MarketSnapshotSort,
    MarketStockPool,
    # Intraday feature types
    INTRADAY_BUCKET_OPTIONS,
    INTRADAY_DEFAULT_BUCKET_MINUTES,
    INTRADAY_MAX_TICKERS,
    IntradayFeatureBucket,
    IntradayFeatureSnapshot,
    IntradayTickerFeatures,
    # Execution history types
    EXECUTION_HISTORY_CONTRACT,
    ExecutionHistoryAdapter,
    ExecutionHistoryContract,
    ExecutionHistoryKeyContract,
    ExecutionHistorySourceContract,
    FillHistoryRow,
    FillHistorySnapshot,
    OrderHistoryRow,
    OrderHistorySnapshot,
    RouteHistoryRow,
    RouteHistorySnapshot,
    ExecutionHistoryFillRow,
    ExecutionHistoryFillSnapshot,
    ExecutionHistoryOrderSummaryRow,
    ExecutionHistoryOrderSummarySnapshot,
    ExecutionHistoryRouteSummaryRow,
    ExecutionHistoryRouteSummarySnapshot,
    # Analytics re-exports (owned by CostView)
    ScorecardCohortMetrics,
    ScorecardFilters,
    ScorecardReport,
    TcaFilters,
    TcaReport,
    # Handoff contracts (WBS-08)
    BrokerStrategyRecommendation,
    ExecutionCandidateHandoff,
    ExecutionPostTradeHandoff,
    HandoffExchangeAdapter,
    HandoffMetadata,
    get_shared_handoff_exchange,
)

__all__ = [
    "CostViewAnalyticsAdapter",
    "ExecutionOperationalDataAdapter",
    "MarketReferenceDataAdapter",
    "PlatformDataAccess",
    "build_platform_data_access",
    "MarketAlert",
    "MarketCandidatePayload",
    "MarketCandidateRow",
    "MarketDailySnapshotRow",
    "MarketSnapshot",
    "MarketSnapshotFilters",
    "MarketSnapshotSort",
    "MarketStockPool",
    "INTRADAY_BUCKET_OPTIONS",
    "INTRADAY_DEFAULT_BUCKET_MINUTES",
    "INTRADAY_MAX_TICKERS",
    "IntradayFeatureBucket",
    "IntradayFeatureSnapshot",
    "IntradayTickerFeatures",
    "EXECUTION_HISTORY_CONTRACT",
    "ExecutionHistoryAdapter",
    "ExecutionHistoryContract",
    "ExecutionHistoryKeyContract",
    "ExecutionHistorySourceContract",
    "FillHistoryRow",
    "FillHistorySnapshot",
    "OrderHistoryRow",
    "OrderHistorySnapshot",
    "RouteHistoryRow",
    "RouteHistorySnapshot",
    "ExecutionHistoryFillRow",
    "ExecutionHistoryFillSnapshot",
    "ExecutionHistoryOrderSummaryRow",
    "ExecutionHistoryOrderSummarySnapshot",
    "ExecutionHistoryRouteSummaryRow",
    "ExecutionHistoryRouteSummarySnapshot",
    "ScorecardCohortMetrics",
    "ScorecardFilters",
    "ScorecardReport",
    "TcaFilters",
    "TcaReport",
    "BrokerStrategyRecommendation",
    "ExecutionCandidateHandoff",
    "ExecutionPostTradeHandoff",
    "HandoffExchangeAdapter",
    "HandoffMetadata",
    "get_shared_handoff_exchange",
]